---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "on-comment"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-xhl46"
    pipelinesascode.tekton.dev/on-comment: "^/hello-world"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: "The Task name is Task"
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["/bin/echo", "{{ trigger_comment }}"]
