---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "pipelinerun-cel-annotation-for-title-match-uzyl"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-push-dhk5v"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && event_title.startsWith("Testing GitHub")
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["/bin/echo", "HELLOMOTO"]
